### ISSUE TITLE
Add Ord Position, Ord Ply, Ord QuadBitboard

### ISSUE THREAD

**Issue by phadej** [mlang/chessIO#8]
```haskell
instance Ord Position where
  compare a b =
      compare (qbb a) (qbb b) <>
      compare (color a) (color b) <>
      compare (flags a) (flags b)
```

Ord for `Ply` can be simply derived

**Comment by phadej** [comment]
As a side comment, after I fixed the recent issues I opened in my local fork I was able to migrate from my heavily modified 0.6.1.0 to 0.7.0.0. Thank you for incorporating my suggestions and making the release!

**Comment by mlang** [comment]
I haven't defined Ord for Position and Ply because I really dont know
what that would actually mean.  Having Ord for Color is already
sort of weird, but too useful for indexing to not do it.
What would be your use case for compare on Position and Ply?

**Comment by phadej** [comment]
Don't think too hard about what the `Ord` total order is. In these cases they are some total order, so it's possible to use algorithms which need `Ord`, e.g. `Map`.

My POV on `Map` vs HashMap is written down in https://oleg.fi/gists/posts/2021-05-19-dont-default-to-hashmap.html
